apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapp-dep2
spec:
  selector:
    matchLabels:
      app: sapp2
  replicas: 2
  template:
    metadata:
      labels:
        app: sapp2
        type: backgend2
    spec:
      containers:
        - name: scont
          image: sivashree03/sapp:tagname
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
